### ISSUE TITLE
std() and var() throw errors for StreamStats.Var

### ISSUE THREAD

**Issue by tawheeler** [johnmyleswhite/StreamStats.jl#20]
Calling `std()` on a `StreamStats.Var` instance throws an error:

```
julia> std(a)
ERROR: `start` has no method matching start(::Var)
 in var at statistics.jl:42
```

```
julia> var(a)
ERROR: `start` has no method matching start(::Var)
 in var at statistics.jl:42
```

There is no issue with `mean(a)`

Not sure what the problem is, maybe it conflicts with a type in statistics.jl?

**Comment by johnmyleswhite** [comment]
Isn't this exactly the behavior you'd expect from reading through the code?

**Comment by johnmyleswhite** [comment]
Is this an issue with an older version of the code? There is no `StreamStats.Var` type anymore.

**Comment by tawheeler** [comment]
aha!
Thanks - I should have checked for that.
I just followed the tutorial on the main page.

Looks like the version I have from Metadata does not have those changes.

**Comment by johnmyleswhite** [comment]
Yes, this package is still very much in flux. Sorry for the confusion.
