### ISSUE TITLE
no StreamStats.jl on repo?

### ISSUE THREAD

**Issue by paulanalyst** [johnmyleswhite/StreamStats.jl#8]
julia> Pkg.add("StreamStats")
ERROR: unknown package StreamStats
 in wait at task.jl:51
 in sync_end at task.jl:315
 in add at pkg/entry.jl:323
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:30
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20

Pkg.available()
...
Sparklines
SpecialMatrices
SQLite
Stan
Stats
StatsBase
StatsdClient
Stochy
StrPack
SuffixArrays
Sundials
SunlightAPIs
SVM
Switch
SymPy
Synchrony
...
Paul

**Comment by johnmyleswhite** [comment]
Did you run `Pkg.update()`?

**Comment by paulanalyst** [comment]
OK, after |Pkg.update() run.
Paul
|W dniu 2015-02-08 o 23:53, John Myles White pisze:
